name: Add Members
description: Issue Forms template to invite members to an Org
title: "Add User to the repo "
labels: ["issueops"]
assignees:
  - decyjphr
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Before adding members to the organization, please refer the
      [Adding members Guidelines](https://github.com/monalisa/project/issues)
      to see if your request will meet the requirements.
- type: textarea
  id: members
  attributes:
    label: Members
    description: |
      Add the GitHub handle for persons; one person per line.
    placeholder: |
      Example: 
      @user1
      @user2
  validations:
    required: true
- type: textarea
  id: teams
  attributes:
    label: Teams to add the members 
    description: "Add the teams. One team per line."
    placeholder: |
      @octodemo/[TEAM]
      @octodemo/[TEAM] 
  validations:
    required: true
