name: Test Action

on:
  issues:
    types: [opened, reopened, labeled]    
jobs:
  test:
    name: Test Action
    if: contains(github.event.issue.labels.*.name, 'issueops')

    runs-on: ubuntu-20.04
    
    steps:
    - id: parse
      name: Run Issue form parser
      uses: peter-murray/issue-forms-body-parser@v2.0.0
      with:
        issue_id: ${{ github.event.issue.number }}
        separator: '###'
        label_marker_start: '>>'
        label_marker_end: '<<' 

    - name: Show parsed data JSON
      run: |
        echo "${{ steps.parse.outputs.payload }}"

    - name: Create GitHub repo
      uses: actions/github-script@v5
      env:
          payload: '${{ steps.parse.outputs.payload }}'
      with:
        script: |
            const {payload} = process.env
            //console.log(context.payload.issue.body)
            console.log(payload)
            let s = JSON.parse(payload)
            console.log(`${JSON.stringify(s)}`)
